# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"kitty" = ""
"ghostty" = ""
"termite" = ""
"code-oss" = ""

"github" = ""
"rust" = ""
"discord" = ""
"vesktop" = ""
"signal" = "󰿌"


# Games Things
"steam" = ""
"wine" = ""
"bh.x86_64" = ""

"google" = ""
"firefox" = ""
"chrome" = ""
"vivaldi" = ""

"file manager" = ""
"libreoffice calc" = ""
"libreoffice writer" = "󰈙"
"obsidian" = "󰈙"
"libreoffice" = "󰏆"

"nvim" = ""
"gthumb" = ""
"menu" = ""

"calculator" = ""
"transmission" = ""
"qbittorrent" = ""

"feh" = ""
"gimp" = ""
"videostream" = ""
"mpv" = ""
"plex" = "󰚺"
"syncplay" = "󰚺"
"music" = ""
"cider" = ""
"pavucontrol" = "󱄡"


"disk usage" = ""
".pdf" = ""
"mupdf" = ""
"okular" = ""



[other]
fallback_icon = "🤨"
deduplicate_icons = true
separator = ": "
